### *Part A*

In [1]:
# 1. What is two to the power of five
2**5

32

In [2]:
# 2. Create a vector with the following data points 23,27,.25,45,61
import numpy as np
v = np.array([23,27,25,45,61])
v

array([23, 27, 25, 45, 61])

In [3]:
# 3. Assign names to the above data points in the vector relating to the day of the week with Mon, Tues, Wed. etc_
day_vector = {'Monday': v[0], 'Tuesday': v[1], 'Wednesday': v[2], 'Thursday': v[3], 'Friday': v[4]}
day_vector

{'Monday': 23, 'Tuesday': 27, 'Wednesday': 25, 'Thursday': 45, 'Friday': 61}

In [4]:
# 4. What is the average/ mean of the values in Vector formed in Q2
v.mean()

36.2

In [5]:
# 5. Find the day when the value is highest

max_value = max(day_vector, key = day_vector.get)
max_value

'Friday'

### *Part B*

In [6]:
# 1. Create a function that takes in a name as a string argument and return a string of the form 'Hello name'

def Hello_name(name):
    return f'Hello {name}'
Hello_name('Karn')    

'Hello Karn'

In [29]:
# 2. Create a function that accepts two arguments, an integer, and a vector of integers. It returns the 
# count of the number of occurances of the integer in the input vector.

def occurance(n, arr):
    count =0
    for i in range(len(arr)):
        if n == arr[i]:
            count += 1
    print(count)


In [30]:
arr = np.array([2,3,2,3,2,2,2])
n = 2
occurance(2, arr)

5


In [93]:
# 3. Create a function that accepts 3 integer values and returns their sum. However if an integer value is evenly divisible by 3,
# then it does not count towards the sum. Return zero if all numbers are evenly divisible by 3.
def sum_div(a,b,c):
    if type(a) == int and type(b) == int and type(c) == int:
        print('First Number:',a)
        print('Second Number:',b)
        print('Third Number:',c)
        if a%3 != 0 and b%3 != 0 and c%3 != 0:
            print(f'The sum of the numbers {a}, {b} and {c} is {a+b+c}')
        elif a%3 == 0 and b%3 != 0 and c%3 != 0:
            print('The first number is ignored as it is divisible by 3')
            print(f'The sum of the numbers {b} and {c} is {b+c}')
        elif a%3 != 0 and b%3 == 0 and c%3 != 0:
            print('The second number is ignored as it is divisible by 3')
            print(f'The sum of the numbers {a} and {c} is {a+c}')
        elif a%3 != 0 and b%3 != 0 and c%3 == 0:
            print('The third number is ignored as it is divisible by 3')
            print(f'The sum of the numbers {a} and {b} is {a+b}')
        elif a%3 == 0 and b%3 == 0 and c%3 != 0:
            print('The first and second number is ignored as it is divisible by 3')
            print(f'The sum is {c}')
        elif a%3 != 0 and b%3 == 0 and c%3 == 0:
            print('The second and second number is ignored as it is divisible by 3')
            print(f'The sum is {c}')
        elif a%3 == 0 and b%3 != 0 and c%3 == 0:
            print('The first and third number is ignored as it is divisible by 3')
            print(f'The sum is {c}')
        else:
            return 0
    else:
        print('Error!! Enter only integer values')

In [101]:
sum_div(8, 2, 3)

First Number: 8
Second Number: 2
Third Number: 3
The third number is ignored as it is divisible by 3
The sum of the numbers 8 and 2 is 10


In [107]:
# Create a function that will return TRUE if an input integer is a prime. Otherwise return fals.

def is_prime_number(a):
    if a >= 2:
        for i in range(2,a):
            if not ( a % i ):
                return False
    else:
        return False
    return True

In [108]:
is_prime_number(9)

False

### *Part C*

In [116]:
# 1. Create two vectors A and B, where A is [1,2,3] and B is [4,5,6]. With these vectors, use c_bind or r_bind function to 
# create 2*3 matrix from vectors

# There are no c_bind or r_bind functions in python. In python we use vstack or hstack to create matrix from vectors.
# To create a 2*3 matrix, vstack has been used. 

A = np.array([1,2,3])
B = np.array([4,5,6])
c = np.vstack((A,B))
c, c.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [131]:
# 2. Create A 5 By 5 Matrix Consisting Of The Numbers 1-25 And Assign It To The Variable Mat2. 
# The Top Row Should Be The Numbers 1-5.

mat2 = np.arange(1,26).reshape(5, 5)
mat2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [136]:
# 3. Grab subsection of [7,8] and [12,13] from mat2

mat2[1][1:3], mat2[2][1:3]

(array([7, 8]), array([12, 13]))